Fix merge conflicts
Mostly re-doing the addition of systemd packages due to the different
base images

diff --git a/dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl b/dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
--- a/dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
+++ b/dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
@@ -79,9 +79,8 @@ FROM {{ .from }}
 
 ENV BEAT_SETUID_AS={{ .user }}
 
-<<<<<<< HEAD
 {{- if (and (contains .from "redhat/ubi") (contains .from "-minimal")) }}
-RUN for iter in {1..10}; do microdnf update -y && microdnf install -y tar gzip findutils shadow-utils && microdnf clean all && exit_code=0 && break || exit_code=$? && echo "microdnf error: retry $iter in 10s" && sleep 10; done; (exit $exit_code)
+RUN for iter in {1..10}; do microdnf update -y && microdnf install -y tar gzip findutils shadow-utils systemd && microdnf clean all && exit_code=0 && break || exit_code=$? && echo "microdnf error: retry $iter in 10s" && sleep 10; done; (exit $exit_code)
 {{- end }}
 
 {{- if contains .from "ubuntu" }}
@@ -90,15 +89,13 @@ RUN for iter in {1..10}; do microdnf update -y && microdnf install -y tar gzip f
 RUN touch /var/mail/ubuntu && chown ubuntu /var/mail/ubuntu && userdel -r ubuntu
 RUN for iter in {1..10}; do \
         apt-get update -y && \
-        DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes ca-certificates curl gawk xz-utils && \
+        DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes ca-certificates curl gawk xz-utils systemd && \
         apt-get clean all && \
         exit_code=0 && break || exit_code=$? && echo "apt-get error: retry $iter in 10s" && sleep 10; \
     done; \
     (exit $exit_code)
 {{- end }}
 
-=======
->>>>>>> fd33d8569 (Enable Filebeat's Journald input in some docker image variants (#7995))
 {{- if contains .from "wolfi" }}
 RUN for iter in {1..10}; do \
         apk update && \
@@ -106,24 +103,6 @@ RUN for iter in {1..10}; do \
         exit_code=0 && break || exit_code=$? && echo "apk error: retry $iter in 10s" && sleep 10; \
     done; \
     (exit $exit_code)
-{{- end }}
-
-# Add Systemd only to: elastic-agent, elastic-agent-complete, ubi, and otel collector.
-# Systemd is not added to any of the wolfi or slim images/variants
-{{- if (not (contains .from "wolfi")) }}
-  {{- if (or (contains .Variant "basic") (contains .Variant "ubi") (contains .Variant "elastic-otel-collector") (contains .Variant "complete"))  }}
-  RUN for iter in {1..10}; do \
-          microdnf update -y && \
-          microdnf install -y tar gzip findutils shadow-utils ca-certificates gawk libcap xz systemd && \
-          microdnf clean all && \
-          exit_code=0 && break || exit_code=$? && echo "microdnf error: retry $iter in 10s" && sleep 10; done; (exit $exit_code)
-  {{- else }}
-  RUN for iter in {1..10}; do \
-          microdnf update -y && \
-          microdnf install -y tar gzip findutils shadow-utils ca-certificates gawk libcap xz && \
-          microdnf clean all && \
-          exit_code=0 && break || exit_code=$? && echo "microdnf error: retry $iter in 10s" && sleep 10; done; (exit $exit_code)
-  {{- end }}
 {{- end }}
 
 LABEL \
@@ -274,32 +253,12 @@ USER root
 # We don't use npx playwright install-deps because that could pull a newer version
 # Install additional fonts as well
 RUN for iter in {1..10}; do \
-<<<<<<< HEAD
     apt-get update -y && \
     $NODE_PATH/node/lib/node_modules/@elastic/synthetics/node_modules/.bin/playwright install-deps chromium && \
     DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes \
     fonts-noto \
     fonts-noto-cjk && \
     exit_code=0 && break || exit_code=$? && echo "apt-get error: retry $iter in 10s" && sleep 10; \
-=======
-        microdnf -y update && \
-        microdnf -y install fontconfig freetype cairo glib2 gtk3 pango xorg-x11-fonts-misc xorg-x11-fonts-Type1 \
-        at-spi2-atk atk at-spi2-core alsa-lib cups-libs dbus-libs libdrm mesa-libEGL mesa-libgbm nspr nss libX11 \
-        libX11-xcb libxcb libXcomposite libXdamage libXext libXfixes libXrandr libxkbcommon libxshmfence glib2 \
-        dbus-glib libicu mesa-libGL unzip iptables && \
-        mkdir -p /usr/share/fonts/google-noto && \
-        curl -LO https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJKjp-hinted.zip && \
-        unzip NotoSansCJKjp-hinted.zip -d /usr/share/fonts/google-noto && \
-        rm -f NotoSansCJKjp-hinted.zip && \
-        microdnf -y remove unzip && \
-        curl -LO https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf && \
-        mv NotoSans-Regular.ttf /usr/share/fonts/google-noto && \
-        curl -LO https://github.com/googlefonts/noto-emoji/raw/main/fonts/NotoColorEmoji.ttf && \
-        mv NotoColorEmoji.ttf /usr/share/fonts/google-noto && \
-        fc-cache -fv && \
-        microdnf clean all && \
-        exit_code=0 && break || exit_code=$? && echo "microdnf error: retry $iter in 10s" && sleep 10; \
->>>>>>> fd33d8569 (Enable Filebeat's Journald input in some docker image variants (#7995))
     done; \
     (exit $exit_code)
 {{- end }}
