Consolidate package installation

diff --git a/dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl b/dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
--- a/dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
+++ b/dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl
@@ -78,14 +78,6 @@ FROM {{ .from }}
 
 ENV BEAT_SETUID_AS={{ .user }}
 
-{{- if (and (contains .from "redhat/ubi") (contains .from "-minimal")) }}
-RUN for iter in {1..10}; do \
-        microdnf update -y && \
-        microdnf install -y tar gzip findutils shadow-utils ca-certificates gawk libcap xz && \
-        microdnf clean all && \
-        exit_code=0 && break || exit_code=$? && echo "microdnf error: retry $iter in 10s" && sleep 10; done; (exit $exit_code)
-{{- end }}
-
 {{- if contains .from "wolfi" }}
 RUN for iter in {1..10}; do \
         apk fix && \
@@ -101,7 +93,13 @@ RUN for iter in {1..10}; do \
   {{- if (or (contains .Variant "basic") (contains .Variant "ubi") (contains .Variant "elastic-otel-collector") (contains .Variant "complete"))  }}
   RUN for iter in {1..10}; do \
           microdnf update -y && \
-          microdnf install -y systemd && \
+          microdnf install -y tar gzip findutils shadow-utils ca-certificates gawk libcap xz systemd && \
+          microdnf clean all && \
+          exit_code=0 && break || exit_code=$? && echo "microdnf error: retry $iter in 10s" && sleep 10; done; (exit $exit_code)
+  {{- else }}
+  RUN for iter in {1..10}; do \
+          microdnf update -y && \
+          microdnf install -y tar gzip findutils shadow-utils ca-certificates gawk libcap xz && \
           microdnf clean all && \
           exit_code=0 && break || exit_code=$? && echo "microdnf error: retry $iter in 10s" && sleep 10; done; (exit $exit_code)
   {{- end }}
