Update dockerfile.tmpl, perhaps unnecessarily

diff --git a/dev-tools/packaging/templates/docker/Dockerfile.tmpl b/dev-tools/packaging/templates/docker/Dockerfile.tmpl
--- a/dev-tools/packaging/templates/docker/Dockerfile.tmpl
+++ b/dev-tools/packaging/templates/docker/Dockerfile.tmpl
@@ -34,48 +34,6 @@ RUN for iter in {1..10}; do \
     (exit $exit_code)
 {{- end }}
 
-{{- if (and (eq .BeatName "heartbeat") (not (contains .from "ubi-minimal"))) }}
-RUN apt-get update -y && \
-    for iter in {1..10}; do \
-        DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes \
-        libglib2.0-0\
-        libnss3\
-        libnspr4\
-        libatk1.0-0\
-        libatk-bridge2.0-0\
-        libcups2\
-        libdrm2\
-        libdbus-1-3\
-        libxcb1\
-        libxkbcommon0\
-        libx11-6\
-        libxcomposite1\
-        libxdamage1\
-        libxext6\
-        libxfixes3\
-        libxrandr2\
-        libgbm1\
-        libpango-1.0-0\
-        libcairo2\
-        libasound2\
-        libatspi2.0-0\
-        libxshmfence1 \
-        fonts-noto \
-        fonts-noto-cjk && \
-        apt-get clean all && \
-        exit_code=0 && break || exit_code=$? && echo "apt-get error: retry $iter in 10s" && sleep 10; \
-    done; \
-    (exit $exit_code)
-ENV NODE_PATH={{ $beatHome }}/.node
-RUN echo \
-    $NODE_PATH \
-    {{ $beatHome }}/.config \
-    {{ $beatHome }}/.synthetics \
-    {{ $beatHome }}/.npm \
-    {{ $beatHome }}/.cache \
-    | xargs -IDIR sh -c 'mkdir -p DIR && chmod 0770 DIR'
-{{- end }}
-
 LABEL \
   org.label-schema.build-date="{{ date }}" \
   org.label-schema.schema-version="1.0" \
@@ -157,6 +115,15 @@ RUN chown {{ .user }} $NODE_PATH
 USER {{ .user }}
 
 {{- if (and (eq .BeatName "heartbeat") (not (contains .from "ubi-minimal")))  }}
+ENV NODE_PATH={{ $beatHome }}/.node
+RUN echo \
+    $NODE_PATH \
+    {{ $beatHome }}/.config \
+    {{ $beatHome }}/.synthetics \
+    {{ $beatHome }}/.npm \
+    {{ $beatHome }}/.cache \
+    | xargs -IDIR sh -c 'mkdir -p DIR && chmod 0770 DIR'
+
 # Setup synthetics env vars
 ENV ELASTIC_SYNTHETICS_CAPABLE=true
 ENV SUITES_DIR={{ $beatHome }}/suites
@@ -182,7 +149,26 @@ RUN cd /usr/share/heartbeat/.node \
   && curl ${NODE_DOWNLOAD_URL} | tar -xJ --strip 1 -C node \
   && chmod ug+rwX -R $NODE_PATH \
   && npm i -g -f @elastic/synthetics && chmod ug+rwX -R $NODE_PATH
+
+USER root
+
+# Install the deps as needed by the exact version of playwright elastic synthetics uses
+# We don't use npx playwright install-deps because that could pull a newer version
+# Install additional fonts as well
+RUN for iter in {1..10}; do \
+    apt-get update -y && \
+    $NODE_PATH/node/lib/node_modules/@elastic/synthetics/node_modules/.bin/playwright install-deps chromium && \
+    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes \
+    fonts-noto \
+    fonts-noto-cjk && \
+    exit_code=0 && break || exit_code=$? && echo "apt-get error: retry $iter in 10s" && sleep 10; \
+done; \
+(exit $exit_code)
+
+USER 1000
 {{- end }}
+
+
 
 {{- range $i, $port := .ExposePorts }}
 EXPOSE {{ $port }}
